import React from 'react'
import { useState, useEffect } from "react"

import Sidebar from '../../components/layouts/sidebar'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Master.module.css'
import petStyle from './pets.module.css'

//Font awesome icon
import { library } from "@fortawesome/fontawesome-svg-core"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faPlus, faMars, faVirus, faBowlFood, faBath, faHandSparkles, faBell, faHeart, faArrowRight, faArrowLeft} from "@fortawesome/free-solid-svg-icons"
import { faCalendar } from "@fortawesome/free-regular-svg-icons"
import PetsBox from '../../components/box/pets'
import AddPets from '../../components/layouts/add-pets'

function PetsIndex() {
    //Initial variable
    const [error, setError] = useState(null);
    const [isLoaded, setIsLoaded] = useState(false);
    const [items, setItems] = useState([]);
  
    useEffect(() => {
        fetch("http://localhost:9000/getAllPets")
        .then(res => res.json())
        .then(
        (result) => {
            setIsLoaded(true);
            setItems(result.data);
        },
        (error) => {
            setIsLoaded(true);
            setError(error);
        }
        )
    },[])

    //Converter
    const data = Object.values(items);
    const crsl = Math.ceil(data.length / 3);
    const count = 0;
  
    return (
        <div className={styles.container}>
            <Head>
                <title>Zivali</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Sidebar />
                <div className="content_layout" id="main">
                    <h3>Dashboard</h3>
                    <div className={petStyle.pets_control_section}>
                        <button className={petStyle.add_pets} data-bs-toggle="modal" data-bs-target="#addPetsModal"><FontAwesomeIcon icon={faPlus} width="13px"/> Add Pets</button>
                        <AddPets />
                        
                        <div className='col-11 pets_list_section'>
                            <div id="carouselExampleControls" className="carousel slide" data-bs-ride="carousel">
                                <div className="carousel-indicators">
                                    {                                      
                                        Array.apply(null, Array(crsl)).map((val, i, index) => {
                                            if(i == 0){
                                                return (
                                                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" className="active" aria-current="true" aria-label="Slide 1" key={i}></button>
                                                )
                                            } else {
                                                return (
                                                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to={i.toString()} aria-label={"Slides "+ i.toString()} key={i}></button>
                                                )
                                            }
                                        })   
                                    }   
                                </div>
                                <div className="carousel-inner">
                                    {                                        
                                        Array.apply(null, Array(crsl)).map((val, i, index) => {
                                            function getClassCarousel(){
                                                if(i == 0){
                                                    return "carousel-item active";
                                                } else {
                                                    return "carousel-item";
                                                }
                                            }
                                            
                                            return (
                                                <div className={getClassCarousel()} key={i}>
                                                    <div className='row pe-5'>
                                                        <PetsBox props={data} crslLength={i+1}/>
                                                    </div>
                                                </div>
                                            );
                                        })
                                    }
                                </div>
                                <button className="carousel-control prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev" title='Previous'>
                                    <FontAwesomeIcon icon={faArrowLeft} width="20px"/>
                                    <span className="visually-hidden">Previous</span>
                                </button>
                                <button className="carousel-control next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next" title='Next'>
                                <FontAwesomeIcon icon={faArrowRight} width="20px"/>
                                    <span className="visually-hidden">Next</span>
                                </button>
                            </div>

                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
  }
  
  export default PetsIndex;
  